// Minimal single-filter 7z container from DOC/7zFormat.txt, never codec source.
// The oracle alone produces the expected decoded bytes, including malformed
// properties and arbitrary encoded streams. No extracted bytes are executed.
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { crc32 } from 'node:zlib';
import { createHash } from 'node:crypto';

const root = path.dirname(new URL(import.meta.url).pathname);
const oracle = process.env.ORACLE ?? '/dev/shm/z7z-coverage-20260906.QOCJby/7zzs';
const hash = b => createHash('sha256').update(b).digest('hex');
const ids = { delta: [3], swap2: [2, 3, 2], swap4: [2, 3, 4], arm: [3, 3, 5, 1], armt: [3, 3, 7, 1], ppc: [3, 3, 2, 5], sparc: [3, 3, 8, 5], arm64: [10], ia64: [3, 3, 4, 1], riscv: [11] };
function number(n) {
	for (let i = 0; i < 8; i++) {
		if (n < 2 ** (7 + 7 * i)) {
			const out = [(256 - 2 ** (8 - i)) | Math.floor(n / 2 ** (8 * i))];
			for (let j = 0; j < i; j++) out.push(Math.floor(n / 2 ** (8 * j)) & 255);
			return out;
		}
	}
	throw new Error('size exceeds fixture limit');
}
function archive(method, props, encoded) {
	const id = ids[method];
	const header = Buffer.from([
		1, 4, 6, 0, 1, 9, ...number(encoded.length), 0,
		7, 11, 1, 0, 1, id.length | (props.length ? 32 : 0), ...id,
		...(props.length ? [...number(props.length), ...props] : []),
		12, ...number(encoded.length), 0, 8, 0, 0,
		5, 1, 17, 5, 0, 120, 0, 0, 0, 0, 0,
	]);
	const start = Buffer.alloc(32);
	Buffer.from('377abcaf271c0004', 'hex').copy(start);
	start.writeBigUInt64LE(BigInt(encoded.length), 12);
	start.writeBigUInt64LE(BigInt(header.length), 20);
	start.writeUInt32LE(crc32(header), 28);
	start.writeUInt32LE(crc32(start.subarray(12)), 8);
	return Buffer.concat([start, encoded, header]);
}
const report = { oracle, oracle_sha256: hash(fs.readFileSync(oracle)), format: 'https://github.com/ip7z/7zip/blob/main/DOC/7zFormat.txt', cases: [] };
function probe(name, method, props, encoded) {
	const dir = path.join(root, name);
	fs.mkdirSync(dir, { recursive: true });
	const full = archive(method, props, encoded);
	const file = path.join(dir, 'probe.7z');
	fs.writeFileSync(file, full);
	const args = ['x', '-so', file];
	const result = spawnSync(oracle, args, { maxBuffer: 16 * 1024 * 1024 });
	if (result.error) throw result.error;
	fs.writeFileSync(path.join(dir, 'encoded.bin'), encoded);
	fs.writeFileSync(path.join(dir, 'plain.bin'), result.stdout);
	report.cases.push({ name, method, properties: props, command: [oracle, ...args], status: result.status, stderr: result.stderr.toString(), encoded_bytes: encoded.length, decoded_bytes: result.stdout.length, encoded_sha256: hash(encoded), plain_sha256: hash(result.stdout), archive_sha256: hash(full) });
	return result;
}
for (const method of Object.keys(ids)) {
	const encoded = fs.readFileSync(path.join(root, method === 'delta' ? 'delta1' : method, 'encoded.bin'));
	for (const [label, props] of [['none', []], ['one', [0]], ['two', [0, 0]], ['three', [0, 0, 0]], ['zero', [0, 0, 0, 0]], ['unaligned', [1, 0, 0, 0]], ['halfword', [2, 0, 0, 0]], ['page', [0, 16, 0, 0]], ['wrap', [240, 255, 255, 255]], ['five', [0, 0, 0, 0, 0]]]) {
		probe(`props-${method}-${label}`, method, props, encoded);
	}
	// Every possible incomplete final unit, including recognizable opcode bytes.
	for (let n = 1; n < (method === 'ia64' ? 16 : method === 'riscv' ? 8 : 4); n++) {
		probe(`tail-${method}-${n}`, method, method === 'delta' ? [0] : [], encoded.subarray(0, 32 + n));
	}
}
fs.writeFileSync(path.join(root, 'probe-provenance.json'), JSON.stringify(report, null, 2) + '\n');
const zigBytes = bytes => '&.{' + bytes.join(',') + '}';
fs.writeFileSync(path.join(root, 'probes.zig'), '// Generated by probe.mjs. Oracle output, not implementation-derived expectations.\n' +
	'pub const Case = struct { name: []const u8, method: []const u8, props: []const u8, encoded: []const u8, plain: []const u8, accepted: bool };\n' +
	'pub const cases = [_]Case{\n' + report.cases.map(c => `\t.{ .name = "${c.name}", .method = ${zigBytes(ids[c.method])}, .props = ${zigBytes(c.properties)}, .encoded = @embedFile("${c.name}/encoded.bin"), .plain = @embedFile("${c.name}/plain.bin"), .accepted = ${c.status === 0} },`).join('\n') + '\n};\n');
console.log(report.cases.filter(c => c.name.startsWith('props-')).map(c => `${c.name}: status=${c.status}, bytes=${c.decoded_bytes}`).join('\n'));
